/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "agzfmgsgcfngpzbcfsbh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnemZtZ3NnY2ZuZ3B6YmNmc2JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3MTk2NDgsImV4cCI6MjA3NjI5NTY0OH0.5l6VctZrU5RywuRNfEppbfGg-9vtvx-nNCBN-imdm3s"